apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quickwit.fullname" . }}
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
data:
{{- if .Values.config.postgres }}
  postgres.password: {{ required "A valid config.postgres.password is required!" .Values.config.postgres.password | b64enc | quote }}
{{- end }}
{{- if ((.Values.config.storage).s3).secret_access_key }}
  storage.s3.secret_access_key: {{ .Values.config.storage.s3.secret_access_key | b64enc | quote }}
{{- end }}
{{- if ((.Values.config.storage).azure).access_key }}
  storage.azure.access_key: {{ .Values.config.storage.azure.access_key | b64enc | quote }}
{{- end }}
