{{- if .Values.searcher.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickwit.fullname" . }}-searcher
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.searcher.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.searcher.serviceType | default .Values.service.type }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.service.ipFamilies }}
  ipFamilies: {{ .Values.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
    - port: 7280
      targetPort: rest
      protocol: TCP
      name: rest
      {{- $type := .Values.searcher.serviceType | default .Values.service.type }}
      {{- if and (eq $type "NodePort") .Values.searcher.restNodePort }}
      nodePort: {{ .Values.searcher.restNodePort }}
      {{- end }}
    - port: 7281
      targetPort: grpc
      name: grpc
      {{- $type := .Values.searcher.serviceType | default .Values.service.type }}
      {{- if and (eq $type "NodePort") .Values.searcher.grpcNodePort }}
      nodePort: {{ .Values.searcher.grpcNodePort }}
      {{- end }}
  selector:
    {{- include "quickwit.searcher.selectorLabels" . | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickwit.fullname" . }}-headless
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.service.ipFamilies }}
  ipFamilies: {{ .Values.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    # Needed by istio with mTLS mode set to STRICT.
    # The port names must starts with "tcp-" or "udp-" to work...
    # See https://istio.io/latest/docs/ops/common-problems/network-issues/#503-error-while-accessing-headless-services
    - name: udp
      port: 7282
      protocol: UDP
    - name: tcp-http
      port: 7280
      protocol: TCP
    - name: tcp-grpc
      port: 7281
      protocol: TCP
  selector:
    {{- include "quickwit.selectorLabels" . | nindent 4 }}
---
{{- if .Values.indexer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickwit.fullname" . }}-indexer
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.indexer.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.indexer.serviceType | default .Values.service.type }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.service.ipFamilies }}
  ipFamilies: {{ .Values.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
    - port: 7280
      targetPort: rest
      protocol: TCP
      name: rest
      {{- $type := .Values.indexer.serviceType | default .Values.service.type }}
      {{- if and (eq $type "NodePort") .Values.indexer.restNodePort }}
      nodePort: {{ .Values.indexer.restNodePort }}
      {{- end }}
    - port: 7281
      targetPort: grpc
      name: grpc
      {{- $type := .Values.indexer.serviceType | default .Values.service.type }}
      {{- if and (eq $type "NodePort") .Values.indexer.grpcNodePort }}
      nodePort: {{ .Values.indexer.grpcNodePort }}
      {{- end }}
  selector:
    {{- include "quickwit.indexer.selectorLabels" . | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickwit.fullname" . }}-metastore
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.metastore.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.metastore.serviceType | default .Values.service.type }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.service.ipFamilies }}
  ipFamilies: {{ .Values.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
    - port: 7280
      targetPort: rest
      protocol: TCP
      name: rest
      {{- $type := .Values.metastore.serviceType | default .Values.service.type }}
      {{- if and (eq $type "NodePort") .Values.metastore.restNodePort }}
      nodePort: {{ .Values.metastore.restNodePort }}
      {{- end }}
    - port: 7281
      targetPort: grpc
      name: grpc
      {{- $type := .Values.metastore.serviceType | default .Values.service.type }}
      {{- if and (eq $type "NodePort") .Values.metastore.grpcNodePort }}
      nodePort: {{ .Values.metastore.grpcNodePort }}
      {{- end }}
  selector:
    {{- include "quickwit.metastore.selectorLabels" . | nindent 4 }}
---
{{- if .Values.control_plane.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickwit.fullname" . }}-control-plane
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.control_plane.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.control_plane.serviceType | default .Values.service.type }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.service.ipFamilies }}
  ipFamilies: {{ .Values.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
    - port: 7280
      targetPort: rest
      protocol: TCP
      name: rest
      {{- $type := .Values.control_plane.serviceType | default .Values.service.type }}
      {{- if and (eq $type "NodePort") .Values.control_plane.restNodePort }}
      nodePort: {{ .Values.control_plane.restNodePort }}
      {{- end }}
    - port: 7281
      targetPort: grpc
      name: grpc
      {{- $type := .Values.control_plane.serviceType | default .Values.service.type }}
      {{- if and (eq $type "NodePort") .Values.control_plane.grpcNodePort }}
      nodePort: {{ .Values.control_plane.grpcNodePort }}
      {{- end }}
  selector:
    {{- include "quickwit.control_plane.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.janitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickwit.fullname" . }}-janitor
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.janitor.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.janitor.serviceType | default .Values.service.type }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.service.ipFamilies }}
  ipFamilies: {{ .Values.service.ipFamilies | toYaml | nindent 2 }}
  {{- end }}
  ports:
    - port: 7280
      targetPort: rest
      protocol: TCP
      name: rest
      {{- $type := .Values.janitor.serviceType | default .Values.service.type }}
      {{- if and (eq $type "NodePort") .Values.janitor.restNodePort }}
      nodePort: {{ .Values.janitor.restNodePort }}
      {{- end }}
    - port: 7281
      targetPort: grpc
      name: grpc
      {{- $type := .Values.janitor.serviceType | default .Values.service.type }}
      {{- if and (eq $type "NodePort") .Values.janitor.grpcNodePort }}
      nodePort: {{ .Values.janitor.grpcNodePort }}
      {{- end }}
  selector:
    {{- include "quickwit.janitor.selectorLabels" . | nindent 4 }}
{{- end }}
