apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickwit.fullname" . }}-searcher
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 7280
      targetPort: http
      protocol: TCP
      name: http
    - port: 7281
      targetPort: grpc
      name: grpc 
  selector:
    {{- include "quickwit.searcher.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickwit.fullname" . }}-headless
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 7282
      protocol: UDP
      name: discovery
  selector:
    {{- include "quickwit.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quickwit.fullname" . }}-indexer
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 7280
      targetPort: http
      protocol: TCP
      name: http
    - port: 7281
      targetPort: grpc
      name: grpc 
  selector:
    {{- include "quickwit.indexer.selectorLabels" . | nindent 4 }}

