apiVersion: v2
name: quickwit
description: Sub-second search & analytics engine on cloud storage.
type: application
version: 0.7.23
appVersion: v0.8.2
keywords:
  - quickwit
  - search
  - analytics
  - tracing
  - logs
home: https://quickwit.io/
sources:
  - https://github.com/quickwit-oss/quickwit/
icon: https://avatars.githubusercontent.com/u/98504233?s=200&v=4
maintainers:
  - name: Quickwit
    email: hello@quickwit.io
  - name: mkhpalm
    email: mkhpalm@gmail.com
