apiVersion: v2
name: quickwit
description: Open-Source & Cloud-Native Log Management at any scale.
type: application
version: 0.3.0
appVersion: "v0.5.0"
keywords:
- quickwit
home: https://quickwit.io/
sources:
- https://github.com/quickwit-oss/quickwit/
icon: https://avatars.githubusercontent.com/u/98504233?s=200&v=4
maintainers:
- name: mkhpalm
  email: mkhpalm@gmail.com
